### PR TITLE
Jenkins RT Pipeline

### LINKED ISSUE #779: Jenkins Regression Test Pipeline
Add required files for the Jenkins UPP Production Pipeline. Jenkins utilizes a Jenkinsfile present in the branch to provide instructions on the steps for regression testing. Additional utility scripts may be added alongside the update. The epic-cicd-jenkins account may also require additional repository permissions in order to run tests on open pull requests with the required label "Jenkins-run-RT"

This pipeline would streamline the testing process for running regression tests on pull requests that are ready on Hera and Orion. Jet, Gaea, and Hercules will follow after UPP regression tests are verified and enabled on those machines.

### PR DESCRIPTION
**Pull request by FernandoAndrade-NOAA**
This PR addresses #779. 
Three new files have been added into the /ci directory
There should be no baseline changes as this PR is for enhancement of testing functionality.
Allows for Jenkins to run regression tests on open PRs with the "Jenkins-run-RT" label on Hera and Orion

1. Jenkinsfile - instructions for the Jenkins Pipeline to run regression tests on supported machines (currently Hera and Orion)
2. rt-status.py - a utility script to summarize apparent changes in results for test cases after regression tests conclude, outputs to the Jenkins test run console
3. rt.sh - a refactored copy of the regression test script for the pipeline and developers to utilize with added options and use of the EPIC UPP test suite location for supported machines.
3a. from a developer's standpoint, starting regression tests may look like the following (ensuring to be synced with latest develop):
```
cd ci/
./rt.sh -a epic -r `pwd`/rundir -t `pwd`/../
```
The following options have been added to rt.sh:

- a - account to submit jobs with
- w - work directory where job scripts and their output logs will be contained, defaults to the current directory/work-upp
- h - home directory, where the test suite resides. Consists of the data input, output, job cards, timestamps, etc. and defaults to utilizing the EPIC UPP test suite directory for regression testing
- r - run directory, where the tests will be run along with their generated files to compare to current baselines in the home directory. defaults to various locations on machines specified in rt.sh, it may be preferable to adjust the location through this rt.sh option as shown above
- t - test_v, the local path to the UPP test version that will be tested before merging. Should typically be set to the example above for developers to run RTs
- b - git branch for cloning before testing
- u - git url for the PR branch that will be cloned
- c - enable git cloning 

Note: use of options b, u, and c will automatically set test_v to the cloned UPP location and will not typically be needed for developer testing as rt.sh will already be contained within the repository, they're legacy options for regression testing.

### CODE REVIEW

**Comment by FernandoAndrade-NOAA** [comment]
please ignore the review request from being taken out of draft

**Comment by FernandoAndrade-NOAA** [comment]
@WenMeng-NOAA just an FYI, Hera logs have been pushed up with no changes as expected. Orion may need to be put on hold as the disk quota has been exceeded at the moment, so this may need to be pushed back until that's resolved.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA The hera log looks good to me. Thanks for working on this.

**Comment by FernandoAndrade-NOAA** [comment]
@WenMeng-NOAA I've run under an alternative workspace in /work2 to run the Orion tests, which should be fine in the meantime while work1's disk quota is resolved. Orion log is pushed and this should be ready for review/final testing. Please let me know if there's any desired changes and suggestions e.g. different default path values / additional log output (like the rt-status.py output). There should be no changed results. 

One thing to note is that the Jenkins RT Pipeline's configuration is currently hard coded to /work1, so there may still be disk quota hiccups after this is merged until that's fixed.

Thanks!

File: ci/rt.sh [hunk 1]
```diff
@@ -0,0 +1,254 @@
...
+run_rap=yes
+run_hrrr=yes
+run_hafs=yes
+run_rtma=yes
+
+#find machine
+mac=$(hostname | cut -c1-1)
+mac2=$(hostname | cut -c1-2)
+mac3=$(hostname | cut -c1-4)
+if [ $mac = v -o $mac = m  ] ; then   # WCOSS_D (venus and mars)
```
Comment (WenMeng-NOAA) [inline ci/rt.sh]: @FernandoAndrade-NOAA Can you remove this if block for WCOSS_D since this platform was retired.

File: ci/rt.sh [hunk 2]
```diff
@@ -0,0 +1,254 @@
...
+ module load prod-util/1.2.2
+fi
+
+#set working directory
+export workdir=${workdir:-"`pwd`/work-upp-${machine}"}
+rm -rf $workdir
+mkdir -p $workdir
+
+#differentiates for orion and hercules
+export rundir="${rundir}-upp-${machine}"
```
Comment (WenMeng-NOAA) [inline ci/rt.sh]: @FernandoAndrade-NOAA Do you think using "${rundir}/upp-machine" would make it easier for users to clean the temporary space periodically on R&D platforms if they run the UPP RTs by themselves? For example,  /scratch1/NCEPDEV/stmp2/Wen.Meng-upp-HERA  VS  /scratch1/NCEPDEV/stmp2/Wen.Meng/upp-HERA

Comment (FernandoAndrade-NOAA) [reply ci/rt.sh]: That may be a little better organized yes. I can go ahead and update that. The main purpose of this was just to avoid conflicts in the the shared filesystems. Would you have a preference for a different directory name or should /upp-${machine} be fine?

File: ci/rt.sh (hunk 1 above)
Comment (FernandoAndrade-NOAA) [reply ci/rt.sh]: Sure thing! With no explicit WCOSS2 check after removal of 64-67, I'm assuming you have an alternative test script on that machine you've been running RTs with?

Comment (WenMeng-NOAA) [reply ci/rt.sh]: @FernandoAndrade-NOAA Good catching. You might add settings for WCOSS2 as:
```
elif [ $mac = d -o $mac = c ]; then    # WCOSS2
 export machine=WCOSS2
 export homedir=/u/wen.meng/noscrub/ncep_post/post_regression_test_new
 export rundir=/lfs/h2/emc/ptmp/$USER
module load prod_util
```

File: ci/rt.sh (hunk 2 above)
Comment (WenMeng-NOAA) [reply ci/rt.sh]: @FernandoAndrade-NOAA Your update looks good for me.

File: ci/rt.sh (hunk 1 above)
Comment (FernandoAndrade-NOAA) [reply ci/rt.sh]: Added, thanks!

File: ci/rt.sh [hunk 3]
```diff
@@ -0,0 +1,255 @@
...
+elif [ $mac3 = herc ] ; then
+ export machine=HERCULES
+ export homedir=${homedir:-"/work/noaa/epic/UPP"}
+ export rundir=${rundir:-"/work2/noaa/stmp/$USER"}
+ module use /work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-dev-20230717/envs/unified-env/install/modulefiles/Core
+ module load stack-intel/2021.9.0
+ module load stack-intel-oneapi-mpi/2021.9.0
+ module load jasper/2.0.32
+ module load prod-util/1.2.2
+elif [ $mac = d -o $mac = c ]; then # WCOSS2
```
Comment (WenMeng-NOAA) [inline ci/rt.sh]: @FernandoAndrade-NOAA Forgot to mention that WCOSS2 is not using slurm job scheduler. So rt.sh failed on WCOSS2. You may remove this block. We working on that later.

Comment (FernandoAndrade-NOAA) [reply ci/rt.sh]: Sounds good, I'll remove the WCOSS2 lines in the meantime then, thanks for testing that.

**Comment by WenMeng-NOAA** [comment]
The UPP RTs were successfully completed on WCOSS2. No baseline updates are needed in this PR.

**Comment by WenMeng-NOAA** [comment]
@FernandoAndrade-NOAA My RTs on WCOSS2 was completed. Do you need to rerun tests on Hera and Orion? Otherwise, this PR looks good for me now.

**Comment by FernandoAndrade-NOAA** [comment]
> @FernandoAndrade-NOAA My RTs on WCOSS2 was completed. Do you need to rerun tests on Hera and Orion? Otherwise, this PR looks good for me now.

I'll go ahead and do a final rerun just on Hera to ensure the path update for rundir doesn't break anything, but there should be no baseline changes.

**Comment by FernandoAndrade-NOAA** [comment]
No issues in the Hera rerun, and no changes. This should be ready for merging. Thanks for your help @WenMeng-NOAA!

**Comment by WenMeng-NOAA** [comment]
This PR is ready for merging.

**Review by WenMeng-NOAA — APPROVED** [review]
