### PR TITLE
IFI test app updates

### LINKED ISSUE #1468: Update IFI to include changes to test app output
The IFI team has made updates to the app that runs libifi outside of the UPP to include necessary metadata for internal research, such as grid and timing information. We would like to confirm that these changes do not affect the regression tests that confirm that the output from the UPP is the same as the output created by the standalone libifi app.

### PR DESCRIPTION
**Pull request by georgemccabe**
Closes #1468

This PR is meant to test that the changes to the app that runs the IFI FIP tests do not break anything. The changes to the app do not include any science changes. They are changes to allow the IFI team to more easily run libifi internally to test future changes, e.g. including grid and timing metadata to the output files.

### CODE REVIEW

File: ci/jobs-dev/run_ifi_standalone_hrrr_URSA.sh [hunk 1]
```diff
@@ -39,15 +39,15 @@ msg="Starting ifi_standalone_hrrr test"
...
+FIPEXEC=${svndir}/exec/fip_runner
 
 # use the UPP run directory so we get the input files in the expected format
 export startdate=2025063004
 export DATA=$rundir/hrrr_ifi_${startdate}
 cd $DATA
 
 upp_output=cat_vars_0.nc
-ifi_standalone_output=icing-category-output.nc
+ifi_standalone_output=20250630/fip_icing_category.20250630_g_040000_f_00036000.nc
```
Comment (SamuelTrahanNOAA) [inline ci/jobs-dev/run_ifi_standalone_hrrr_URSA.sh:50]: This must remain `icing-category-output.nc` since it has to be compared against the output of UPP. This regression test confirms UPP gets the same result as the libIFI when run directly. Instead, you are comparing it against a different reference file. That defeats the purpose of the regression test.

File: ci/jobs-dev/run_ifi_standalone_rrfs_URSA.sh [hunk 2]
```diff
@@ -40,15 +40,15 @@ msg="Starting ifi_standalone_rrfs test"
...
+FIPEXEC=${svndir}/exec/fip_runner
 
 # use the UPP run directory so we get the input files in the expected format
 export startdate=2025040112
 export DATA=$rundir/rrfs_ifi_${startdate}
 cd $DATA
 
 upp_output=cat_vars_0.nc
-ifi_standalone_output=icing-category-output.nc
+ifi_standalone_output=20250401/fip_icing_category.20250401_g_120000_f_00064800.nc
```
Comment (SamuelTrahanNOAA) [inline ci/jobs-dev/run_ifi_standalone_rrfs_URSA.sh:51]: This must remain `icing-category-output.nc` since it has to be compared against the output of UPP. This regression test confirms UPP gets the same result as the libIFI when run directly. Instead, you are comparing it against a different reference file. That defeats the purpose of the regression test.

**Comment by WenMeng-NOAA** [comment]
@georgemccabe Per the UPP PR processing standard, Could you please open a UPP issue to link to this PR?

**Review by SamuelTrahanNOAA — CHANGES_REQUESTED** [review]
These changes remove the test of whether libIFI internally produces the same output as UPP. Instead, it compares against a different baseline. That eliminates our ability to confirm UPP and libIFI generate the same output.

File: ci/jobs-dev/run_ifi_standalone_hrrr_URSA.sh (hunk 1 above)
Comment (georgemccabe) [reply ci/jobs-dev/run_ifi_standalone_hrrr_URSA.sh:50]: The changes we made to the IFI standalone app changes the output file naming. I thought this variable defines the expected output file that is created by the standalone app, which is compared to the output generated by the UPP defined by `$upp_output`.

Comment (SamuelTrahanNOAA) [reply ci/jobs-dev/run_ifi_standalone_hrrr_URSA.sh:50]: No. That variable points to the expected output file that is created by *UPP*. The three forecast products within the file should match between UPP and the standalone apps. Metadata and dimension names might not match.

Comment (georgemccabe) [reply ci/jobs-dev/run_ifi_standalone_hrrr_URSA.sh:50]: I'm not sure I follow, but I reverted the change. The fip2-lookalike app used to produce a file called `icing-category-output.nc`, but it no longer does, so I don't follow how a file of this name will be created to compare.

Comment (SamuelTrahanNOAA) [reply ci/jobs-dev/run_ifi_standalone_hrrr_URSA.sh:50]: I may have misunderstood. Let me run the scripts so I can see them in action.

Comment (SamuelTrahanNOAA) [reply ci/jobs-dev/run_ifi_standalone_hrrr_URSA.sh:50]: I cannot test this because I cannot access UPP_IFI_RAL.

Comment (georgemccabe) [reply ci/jobs-dev/run_ifi_standalone_hrrr_URSA.sh:50]: @SamuelTrahanNOAA , the branch is now in the origin repo `NCAR/UPP_IFI`

Comment (SamuelTrahanNOAA) [reply ci/jobs-dev/run_ifi_standalone_hrrr_URSA.sh:50]: I'm pretty sure your change is right and my comment is wrong. However, the fip_runner won't run for me from within the regression test. It gives an error about an invalid NetCDF id and exits.

It gives me this log:

```
Read 3D var "ICMR"
Read 3D var "CLWMR"
Read 3D var "GRMR"
Read 3D var "HGT"
Read 3D var "PRES"
Read 3D var "RWMR"
Read 3D var "MIXR"
Read 3D var "TMP"
Read 3D var "SNMR"
Read 3D var "VVEL"
Read 2D var "APCP1Hr"
Read 2D var "CAPE"
Read 2D var "CIN"
NetCDF: Not a valid ID
```

That log file is here:

* Ursa: `/scratch4/BMC/ifi/Samuel.Trahan/fip/georgemccabe-ifi_test_internal/ci/work-upp-URSA-intelllvm/out.post.ifi_standalone_hrrr`

and the job ran here:

* Ursa: /scratch4/BMC/ifi/Samuel.Trahan/fip/scrub/upp-URSA/hrrr_ifi_2025063004/

You can find the UPP output, but not the output from fip_runner since it promptly aborted.

File: ci/jobs-dev/run_ifi_standalone_rrfs_URSA.sh (hunk 2 above)
Comment (SamuelTrahanNOAA) [reply ci/jobs-dev/run_ifi_standalone_rrfs_URSA.sh:51]: I'm about 90% certain my comment is incorrect and @georgemccabe's change was right. However, I've been unable to run this test due to a NetCDF error to confirm that.

File: ci/jobs-dev/run_ifi_standalone_hrrr_URSA.sh (hunk 1 above)
Comment (georgemccabe) [reply ci/jobs-dev/run_ifi_standalone_hrrr_URSA.sh:50]: I don't have permission to view the `/scratch4/BMC/ifi/Samuel.Trahan/fip` directory on Ursa.

Could you share the path to the UPP output file `hybr_vars_0.nc` that is passed into fip_runner? I tested this using the output from the fip2-lookalike app, but not the actual UPP output.

I'm guessing this has to do with the lack of a "time" variable that is read to determine the valid time of the model data.

Comment (georgemccabe) [reply ci/jobs-dev/run_ifi_standalone_hrrr_URSA.sh:50]: It sounds like the UPP output is in the directory you listed, so I would just need permission to view the contents. I can find the correct path.

Comment (SamuelTrahanNOAA) [reply ci/jobs-dev/run_ifi_standalone_hrrr_URSA.sh:50]: @georgemccabe - I contacted you directly by email about the file access problem.

**Review by SamuelTrahanNOAA — APPROVED** [review]
With the recent changes to this branch and the libIFI dependency PR, the regression tests run for me now.

File: ci/jobs-dev/run_ifi_standalone_hrrr_URSA.sh (hunk 1 above)
Comment (SamuelTrahanNOAA) [reply ci/jobs-dev/run_ifi_standalone_hrrr_URSA.sh:50]: After some changes to libIFI.fd and IFI.F from @georgemccabe, the UPP and fip-runner agree with what should be in the fip-runner input file. His original change (new filename) is correct as well.

**Comment by BenjaminBlake-NOAA** [comment]
@SamuelTrahanNOAA  IFI will not be included with RRFSv1, so I am wondering if we should consider removing the RRFS IFI tests from UPP.  What do you think?

**Comment by SamuelTrahanNOAA** [comment]
>  IFI will not be included with RRFSv1, so I am wondering if we should consider removing the RRFS IFI tests from UPP. What do you think?

I agree. It's best not to burden ourselves with supporting obsolete configurations when our labor and compute resources are steadily shrinking.

**Comment by BenjaminBlake-NOAA** [comment]
> I agree. It's best not to burden ourselves with supporting obsolete configurations when our labor and compute resources are steadily shrinking.

Sounds good to me.  I can do this in a separate PR.

**Comment by SamuelTrahanNOAA** [comment]
I've looked at the regression tests, and removing the rrfs ifi is not a small change, so it should be in a separate PR. I've made an attempt in a local working copy and I'll check if it works.

**Comment by SamuelTrahanNOAA** [comment]
@BenjaminBlake-NOAA - Sorry, I started my work before I noticed your response. You'll be able to do this quicker, I expect, so I'll wait to hear back from you.

**Comment by BenjaminBlake-NOAA** [comment]
> @BenjaminBlake-NOAA - Sorry, I started my work before I noticed your response. You'll be able to do this quicker, I expect, so I'll wait to hear back from you.

No problem - yeah I should be able to do this soon.

**Comment by BenjaminBlake-NOAA** [comment]
@clyden-noaa This PR is ready for testing on the RDHPCs.  There are no baseline changes expected to the UPP RTs.  Thanks!

Also, it looks like the read the docs build failed with my commit to upload the WCOSS2 RT log - I'm not sure what that is about.

**Review by clyden-noaa — APPROVED** [review]
@WenMeng-NOAA @BenjaminBlake-NOAA @georgemccabe 
My testing is now complete
All of the RTs ran successfully on all RDHPC systems
All RTs finished within established timing thresholds
There were no baseline changes

**Comment by clyden-noaa** [comment]
> @clyden-noaa This PR is ready for testing on the RDHPCs. There are no baseline changes expected to the UPP RTs. Thanks!
> 
> Also, it looks like the read the docs build failed with my commit to upload the WCOSS2 RT log - I'm not sure what that is about.

@BenjaminBlake-NOAA I noticed that the docs build had failed.
This was the actual error:
```Read the Docs build information
Build id: 31880301
Project: upp
Version: 1467
Commit: 4e96912052331a72e626490bc4f29ec6c5ee6b1a
Date: 2026-03-19T14:16:51.024382Z
State: finished
Success: False


[rtd-command-info] start-time: 2026-03-19T14:16:51.503190Z, end-time: 2026-03-19T14:16:52.128828Z, duration: 0, exit-code: 0
git clone --depth 1 https://github.com/NOAA-EMC/UPP .
Cloning into '.'...

[rtd-command-info] start-time: 2026-03-19T14:16:52.169957Z, end-time: 2026-03-19T14:16:52.582547Z, duration: 0, exit-code: 0
git fetch origin --force --prune --prune-tags --depth 50 pull/1467/head:external-1467
From https://github.com/NOAA-EMC/UPP
 * [new ref]         refs/pull/1467/head -> external-1467

[rtd-command-info] start-time: 2026-03-19T14:16:52.699321Z, end-time: 2026-03-19T14:16:52.739785Z, duration: 0, exit-code: 128
git checkout --force 4e96912052331a72e626490bc4f29ec6c5ee6b1a
fatal: reference is not a tree: 4e96912052331a72e626490bc4f29ec6c5ee6b1a
```
This is your commit hash, so I'm not quite sure what happened. It seems to have built okay with my commits.

**Review by BenjaminBlake-NOAA — APPROVED** [review]
@clyden-noaa Thanks for testing!  I'm also not sure why the read the docs build failed with my commit, but since it works for you I think we are good to proceed with merging this PR.
