### PR TITLE
Fix test for CALLCL()

### LINKED ISSUE #1432: Unit test works in UPP CI test but breaks for ufsatm
The test program test_callcl.f90 is breaking for certain cases in ufsatm's CI. (see https://github.com/NOAA-EMC/ufsatm/pull/1060)

There appears to be an issue with boundary definitions and maybe some small ulp differences in EXP() and LOG() occurring across environments.

### PR DESCRIPTION
**Pull request by AlysonStahl-NOAA**
Fixes #1432

### CODE REVIEW

**Comment by gspetro-NOAA** [comment]
It would be helpful if this PR could be a priority so that we can include it in the WM UPP hash update PR. That PR depends on this fix.

**Comment by WenMeng-NOAA** [comment]
> It would be helpful if this PR could be a priority so that we can include it in the WM UPP hash update PR. That PR depends on this fix.

@gspetro-NOAA We will process this one soon.

File: unit_tests/test_callcl.f90 [hunk 1]
```diff
@@ -39,50 +44,60 @@ program test_callcl
...
+    fis(2,2) = 5000.0/gi
+    EXP_ZLCL(2,2) = 0.0
+    
     call callcl(P1D, T1D, Q1D, PLCL, ZLCL)
 
-    ! Check results
     res = 0
-    do j = jsta, jend
-        do i = ista, iend
+    do i = ista, iend
```
Comment (WenMeng-NOAA) [inline unit_tests/test_callcl.f90:93]: @AlysonStahl-NOAA May I ask for the intention of changing the i,j loop order?

Comment (JesseMeng-NOAA) [reply unit_tests/test_callcl.f90:93]: @WenMeng-NOAA  @AlysonStahl-NOAA 
I believe this is not intentional and it should not affect the results.
Recommend to switch the order of i and j loops for consistency.

Comment (BenjaminBlake-NOAA) [reply unit_tests/test_callcl.f90:93]: @AlysonStahl-NOAA After discussing with @WenMeng-NOAA we'd like to get this PR merged as soon as possible.  We recommend this minor change be made in your PR #1428

**Review by BenjaminBlake-NOAA — APPROVED** [review]
Regression tests passed on all supported platforms with no baseline changes - this bug fix PR is ready for merging.

**Review by WenMeng-NOAA — APPROVED** [review]

File: unit_tests/test_callcl.f90 (hunk 1 above)
Comment (AlysonStahl-NOAA) [reply unit_tests/test_callcl.f90:93]: @JesseMeng-NOAA @WenMeng-NOAA Correct, this wasn't intentional. I just rewrote the test from scratch. It just changes the comparison order and nothing else. 

I can change it in my new PR, but I haven't kept track of that consistency in my other unit tests because it really makes no difference in the test.

Comment (gspetro-NOAA) [reply unit_tests/test_callcl.f90:93]: In general, it seems like the convention is to do **i** first before **j** in most code, and it might be good to stick to that going forward just so it doesn't throw off anyone who reads the code. (Obviously, there can be specific use cases that require the reverse order.) Not sure it's worth scouring your previous tests and redoing anything you find, but it could be good to change this one, since it's been identified, and stick to i first, then j in tests going forward. Just my two cents.
